### ISSUE TITLE
似たような処理を繰り返して書いているので、for文などでまとめた方が良いと思います。

### ISSUE THREAD

**Issue by C0A21007** [c0a21160/ProjExD#4]
https://github.com/c0a21160/ProjExD/blob/a91060cf3db03040a28af69a5aee0f8e39370166/ex02/calc.py#L40

**Comment by c0a21160** [comment]
省略は考えていたのですが、例題のfor ope in operators:の部分の仕組みを上手く纏めること出来ずに同じような処理を行う結果となってしまっています。ご指摘有難うございます。
