### ISSUE TITLE
operaterが毎回宣言されているのはもったいないので、まとめた方がいいと思います

### ISSUE THREAD

**Issue by kouki0412** [c0a21160/ProjExD#5]
https://github.com/c0a21160/ProjExD/blob/a91060cf3db03040a28af69a5aee0f8e39370166/ex02/calc.py#L41

**Comment by c0a21160** [comment]
for文などを使用し処理をまとめることも考えていたのですが、例題のfor ope in operators:を参考にさせて頂いた内部の「＋」「ー」のみだけを上手く繰り返すことが出来ずにこのようなやり方になってしまっています。自身の力不足でした。ご指摘ありがとうございます。
