### ISSUE TITLE
使わないコードなら消した方がいいと思います

### ISSUE THREAD

**Issue by C0A21007** [c0a21160/ProjExD#6]
https://github.com/c0a21160/ProjExD/blob/e93300a2900d99801be2295fcfcdc5828ac8a0ba/ex03/maiz.py#L16

**Comment by c0a21160** [comment]
今回は採用できていなかったのですがUPキーを使用するような新しい変更を行う可能性があったためコードを残したままとなっていました。ご指摘ありがとうございます。
